version: 2
jobs:
  build:
  ruby:
    version: 2.3
  machine: true
    environment:
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true # speeds up installation of html-proofer

  dependencies:
    post:
      - bundle exec jekyll build

  test:
    post:
      - bundle exec htmlproofer ./_site --allow-hash-href --check-favicon --check-html --disable-external
